# Generated by Django 5.1.7 on 2025-03-19 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('APV', 'Approved'), ('RJCT', 'Rejected')], default='PEN', max_length=4)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('registration_place', models.CharField(max_length=255)),
                ('legal_representative', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('credit_code', models.CharField(max_length=18, unique=True)),
                ('entity_type', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('PLT', 'Plaintiff'), ('DEF', 'Defendant'), ('TP', 'Third Party')], max_length=3)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('work_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('domicile_address', models.CharField(max_length=255)),
                ('usual_residence', models.CharField(blank=True, max_length=255, null=True)),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('PLT', 'Plaintiff'), ('DEF', 'Defendant'), ('TP', 'Third Party')], max_length=3)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_persons', to='cases.case')),
            ],
        ),
    ]
