# Generated by Django 5.1.7 on 2025-03-22 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': '案件', 'verbose_name_plural': '案件'},
        ),
        migrations.AlterModelOptions(
            name='legalentity',
            options={'verbose_name': '法人', 'verbose_name_plural': '法人'},
        ),
        migrations.AlterModelOptions(
            name='naturalperson',
            options={'verbose_name': '自然人', 'verbose_name_plural': '自然人'},
        ),
        migrations.AddField(
            model_name='case',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='ethnicity',
            field=models.CharField(default=0, max_length=50, verbose_name='民族'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='case',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(verbose_name='案件描述'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('PEN', '待审核'), ('APV', '已通过'), ('RJCT', '已拒绝')], default='PEN', max_length=4, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255, verbose_name='案件标题'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='address',
            field=models.CharField(max_length=255, verbose_name='住所地'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entities', to='cases.case', verbose_name='所属案件'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='credit_code',
            field=models.CharField(max_length=18, unique=True, verbose_name='统一社会信用代码'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='entity_type',
            field=models.CharField(max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='legal_representative',
            field=models.CharField(max_length=100, verbose_name='法定代表人'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='position',
            field=models.CharField(max_length=100, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='registration_place',
            field=models.CharField(max_length=255, verbose_name='注册地'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='role',
            field=models.CharField(choices=[('PLT', '原告'), ('DEF', '被告'), ('TP', '第三人')], max_length=3, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natural_persons', to='cases.case', verbose_name='所属案件'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='date_of_birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='domicile_address',
            field=models.CharField(max_length=255, verbose_name='住所地'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='id_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='证件号码'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='id_type',
            field=models.CharField(max_length=50, verbose_name='证件类型'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='职务'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='role',
            field=models.CharField(choices=[('PLT', '原告'), ('DEF', '被告'), ('TP', '第三人')], max_length=3, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='usual_residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='经常居住地'),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='work_unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作单位'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LAW', '律师'), ('ADM', '管理员')], max_length=3)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
