# Generated by Django 5.1.7 on 2025-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_options_alter_legalentity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('LAW', '律师'), ('ADM', '管理员')], default='LAW', max_length=3),
        ),
    ]
